### ISSUE TITLE
[error]Pole not balanced. Stopping after 50 failures

### ISSUE THREAD

**Issue by ayan1991** [famalgosner/roboticsControl#3]
hi,I had trial again by again ,but failed all,my model is the big segway model in verp,
so ,is there anything i haven't do right? 
`Pole not balanced. Stopping after 50 failures`

**Comment by beckerpascal** [comment]
Hey @ayan1991,
I will check what might be your problem and how to solve in the next few days.
In the mean time: Could you provide me with more information about your setup?
Which OS?
Which python version?
Which Vrep version?

Cheers

**Comment by ayan1991** [comment]
V-REP PRO EDU,Version 3.3.2 
OS:windows7 64bit
python :3.7.1

**Comment by beckerpascal** [comment]
Did you try it with another vrep model? Like middle or normal?
I just ran the simulation with the big model and it worked like expected.

You could also try:
- Update V-REP to 3.6.2
- Try python2

**Comment by beckerpascal** [comment]
No further reaction -> solved.

**Comment by SQRTAxel** [comment]
Hello,
I tried to execute your code on the reinforcement learning part, but I encountered the same problem as @ayan1991 .
Could you specify which version of Python2 you used to execute this code?
